# -*- coding: utf-8 -*-
"""readmissioniqhealthcare_ai.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0pUA_Jd8NWLykK9fl-1m0S173Mzt8iI
"""

"""
ReadmissionIQ

AI-Powered Healthcare Readmission Intelligence

Built with:
- Snowflake
- Snowpark Python
- Snowflake Cortex
- Streamlit
"""

import streamlit as st
from snowflake.snowpark.context import get_active_session

session = get_active_session()

st.title(" ReadmissionIQ")

st.caption(
    "AI-Powered Healthcare Readmission Intelligence"
)

st.markdown("""
Ask questions about:
- Hospital readmission risk
- State-level healthcare trends
- Operational improvement recommendations
- High-risk hospital categories
""")

with st.expander(" Example Questions"):
    st.markdown("""
    - What trends exist in AMI readmissions?
    - Which states have the highest concentration of high readmission rates?
    - Give operational recommendations for reducing COPD readmissions.
    - Summarize hospitals with the highest pneumonia readmission rates.
    - What patterns exist in heart failure readmissions?
    - Which CABG facilities show elevated readmission ratios?
    """)

question = st.text_input("Ask a healthcare readmissions question:")

def get_measure_filter(question):
    q = question.lower()
    if "ami" in q:
        return "AMI"
    elif "heart failure" in q or "heart" in q or "hf" in q:
        return "HF"
    elif "copd" in q:
        return "COPD"
    elif "pneumonia" in q:
        return "PN"
    elif "cabg" in q:
        return "CABG"
    elif "hip" in q or "knee" in q:
        return "HIP-KNEE"
    else:
        return None

measure_filter = get_measure_filter(question) if question else None

def is_in_scope(question):
    q = question.lower()

    keywords = [
        "readmission", "readmissions", "hospital", "hospitals",
        "healthcare", "patient", "patients",
        "ami", "heart", "heart failure", "hf",
        "copd", "pneumonia", "cabg",
        "hip", "knee",
        "risk", "cms", "hrrp",
        "discharge", "care coordination",
        "quality", "clinical"
    ]

    return any(keyword in q for keyword in keywords)

if not is_in_scope(question):

    out_of_scope_query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'claude-4-sonnet',
        'You are ReadmissionIQ, a healthcare readmissions intelligence assistant.

        The user asked:
        "{question}"

        This question is outside your scope.

        Respond in 2-3 friendly sentences:
        - Briefly acknowledge the question.
        - Explain that you specialize in hospital readmissions and healthcare analytics.
        - Suggest the appropriate type of resource without pretending to answer the question.
        - Keep the tone professional and slightly friendly.'
    ) AS RESPONSE
    """

    result = session.sql(out_of_scope_query).collect()

    st.subheader("Analytical Summary")
    st.write(result[0]["RESPONSE"])
    st.stop()

if question:

    where_clause = "WHERE excess_readmission_ratio IS NOT NULL"

    if measure_filter:
        data_query = f"""
            SELECT
                facility_name,
                state,
                measure_name,
                excess_readmission_ratio
            FROM ANALYTICS.HOSPITAL_RISK_SUMMARY
            {where_clause}
            AND measure_name LIKE '%{measure_filter}%'
            ORDER BY excess_readmission_ratio DESC
            LIMIT 10
        """
    else:
        data_query = f"""
            SELECT
                measure_name,
                COUNT(*) AS total_records,
                ROUND(AVG(excess_readmission_ratio), 3) AS avg_readmission_ratio,
                ROUND(MAX(excess_readmission_ratio), 3) AS max_readmission_ratio
            FROM ANALYTICS.HOSPITAL_RISK_SUMMARY
            {where_clause}
            GROUP BY measure_name
            ORDER BY avg_readmission_ratio DESC
        """

    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'claude-4-sonnet',
        'You are a healthcare analytics expert.

        Answer this question using only the data below.

        Question:
        {question}

        Data:
        ' ||
        (
            SELECT LISTAGG(OBJECT_CONSTRUCT(*)::STRING, '\\n')
            FROM (
                {data_query}
            )
        )
        ||
        '

        Provide executive-level insights, trends, and recommendations.
        Do not list individual hospital names unless specifically requested.
        Focus on patterns, operational implications, and business recommendations.'
    ) AS RESPONSE
    """

    result = session.sql(query).collect()

    st.subheader("Analytical Summary")
    st.write(result[0]["RESPONSE"])

st.divider()

st.subheader("Readmissions Performance Overview")

table_where_clause = "WHERE excess_readmission_ratio IS NOT NULL"

if measure_filter:
    table_where_clause += f" AND measure_name LIKE '%{measure_filter}%'"

top_hospitals = session.sql(f"""
SELECT
    facility_name,
    state,
    measure_name,
    excess_readmission_ratio,
    risk_level
FROM ANALYTICS.HOSPITAL_RISK_SUMMARY
{table_where_clause}
ORDER BY excess_readmission_ratio DESC
LIMIT 10
""").to_pandas()

st.dataframe(top_hospitals, use_container_width=True)

st.divider()

st.caption("""
Healthcare Readmission Intelligence Agent

Data Source: CMS Hospital Readmissions Reduction Program (HRRP)

Technology Stack:
Snowflake Cortex • Snowpark • SQL • Streamlit
""")